# Generated by Django 4.2.4 on 2023-08-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_title_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetimr_modified',
            new_name='datetime_modified',
        ),
    ]
